import type { Worker } from "@/app/types/planner";

export const workersList: Omit<Worker, "initials">[] = [
  {
    id: 1,
    name: "Jan de Vries",
    availableFrom: "Jan 8",
    availableTo: "Jan 15",
    fullTimeStr: "1128hr",
    hours: "18hr",
    status: "available",
    days: [
      { label: "m", active: true },
      { label: "di", active: true },
      { label: "w", active: true },
      { label: "do", active: true },
      { label: "vr", active: false },
    ],
  },
  {
    id: 2,
    name: "Pieter van Dijk",
    availableFrom: "Jan 10",
    availableTo: "Jan 18",
    fullTimeStr: "980hr",
    hours: "14hr",
    status: "on leave",
    days: [
      { label: "m", active: false },
      { label: "di", active: false },
      { label: "w", active: true },
      { label: "do", active: true },
      { label: "vr", active: true },
    ],
  },
  {
    id: 3,
    name: "Marieke Jansen",
    availableFrom: "Jan 12",
    availableTo: "Jan 22",
    fullTimeStr: "1040hr",
    hours: "16hr",
    status: "available",
    days: [
      { label: "m", active: true },
      { label: "di", active: true },
      { label: "w", active: false },
      { label: "do", active: true },
      { label: "vr", active: false },
    ],
  },
  {
    id: 4,
    name: "Anita van den Berg",
    availableFrom: "Jan 9",
    availableTo: "Jan 16",
    fullTimeStr: "1100hr",
    hours: "20hr",
    status: "on leave",
    days: [
      { label: "m", active: false },
      { label: "di", active: true },
      { label: "w", active: true },
      { label: "do", active: false },
      { label: "vr", active: true },
    ],
  },
  {
    id: 5,
    name: "Klaas Hendriksen",
    availableFrom: "Jan 14",
    availableTo: "Jan 25",
    fullTimeStr: "1200hr",
    hours: "22hr",
    status: "available",
    days: [
      { label: "m", active: true },
      { label: "di", active: false },
      { label: "w", active: true },
      { label: "do", active: true },
      { label: "vr", active: false },
    ],
  },
  {
    id: 6,
    name: "Elisabeth de Wilde",
    availableFrom: "Jan 11",
    availableTo: "Jan 19",
    fullTimeStr: "990hr",
    hours: "15hr",
    status: "available",
    days: [
      { label: "m", active: true },
      { label: "di", active: true },
      { label: "w", active: true },
      { label: "do", active: false },
      { label: "vr", active: false },
    ],
  },
  {
    id: 7,
    name: "Cornelis van Beek",
    availableFrom: "Jan 13",
    availableTo: "Jan 21",
    fullTimeStr: "1080hr",
    hours: "17hr",
    status: "available",
    days: [
      { label: "m", active: true },
      { label: "di", active: false },
      { label: "w", active: true },
      { label: "do", active: true },
      { label: "vr", active: true },
    ],
  },
];
